#!/bin/bash
set -x
if [ ! -d $OPENSHIFT_DATA_DIR/jdk1.8.0_65 ]
then
    cd $OPENSHIFT_DATA_DIR
    wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u65-b17/jdk-8u65-linux-x64.tar.gz
    tar -zxf jdk-8u65-linux-x64.tar.gz
    rm -f jdk-8u65-linux-x64.tar.gz
fi
if [ ! -d $OPENSHIFT_DATA_DIR/gradle-2.10 ]
then
    cd $OPENSHIFT_DATA_DIR
    mkdir gradle
    wget http://services.gradle.org/distributions/gradle-2.10-bin.zip
    unzip gradle-2.10-bin.zip
    rm -f gradle-2.10-bin.zip
fi