#!/bin/bash
set -x
export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0

if [ ! -d $OPENSHIFT_DATA_DIR/gradle-2.10 ]
then
    cd $OPENSHIFT_DATA_DIR
    mkdir gradle
    wget http://services.gradle.org/distributions/gradle-2.10-bin.zip
    unzip gradle-2.10-bin.zip
    rm -f gradle-2.10-bin.zip
fi