language: java

jdk:
    - oraclejdk8

script:
    - gradle
    
addons:
  postgresql: "9.3"

services:
  - postgresql  
  

 before_script:
  - psql -c 'create database itevent_test_db;' -U postgres

  
