language: java
jdk:
- oraclejdk8
script:
- gradle
before_script:
- psql -c 'create database itevent_test_db;' -U postgres
- psql -c 'create database itevent_db;' -U postgres
addons:
  postgresql: '9.3'
services:
- postgresql
env:
  global:
  - itev_database_driver=org.postgresql.Driver
  - itev_database_url=jdbc:postgresql://127.0.0.1:5432/itevent_db
  - itev_database_username=postgres
  - itev_database_password=""
  - itev_changeLogFile=src/main/resources/liquibase/db.changelog-master.xml
  - itev_httpPort=8080
  - itev_stopPort=8081
  - itev_cron_start_sending=10 10 10 10 * *
  - itev_reminderAboutEventForThePeriod=1
  - itev_test_database_driver=org.postgresql.Driver
  - itev_test_database_url=jdbc:postgresql://127.0.0.1:5432/itevent_test_db
  - itev_test_database_username=postgres
  - itev_test_database_password=""
  - itev_test_changeLogFile=src/test/resources/liquibase/db.changelog-create.xml
  - secure: i7UOrvzlFuiP6ZKnf2uIlSp2nAiO6KqKxAIXLJrpOlOwoDOx4AnsK4OfFgcnYWIiEb+dnd8ItsHcpl4AqmEHdxw1FUDRpqO8HSVPfIZTUOjnUShy6p9IyQn8b0tYBJA/BoFlveXcL/q5Y3s/oYzc/QRoJR+KzCuPeslEFa7THHK/8osANmF6YSbPX6WuUPkE7L84ofCZIL7fIu+Nv1ifbeosSc3ZBTxaqJT9bR0MFXONWRMis1Wii5ZjOI7EC5ueH9WIlxSi7Uk/LVTM8158HMvt5seKKiPJVf5O4Jy+hlU0Rb/iMB50iGoYgok7QErI8raA5iV3/1xHiVn8CDG6LDLAf1zPxp+bYuiYXQUL0cWDvbCDCVhbU0h8oWfeN5qRgvIDlWskkvJ6+t3HxJOqW0bbYuS+yHEmwz9aef9NAHAY1f4stXueC1veITs42U65h7VEjey2DLUHbMTeI0Rg41ioV70Pj4DZe15X70oooWNXWYjjYB1TPKo/843D7ktQ7TyeofkVUOhQdHtP86DZUyImLPpu1Ecc390OIeiukv9M0iXdmxHg9J43Yx4rSxovick1F8JKTUTY8VyipFhCjZkzl7/CHPwlcgiCyA01p7UhLDuf2Wot3YpRqAlg1qJNtPshjQy77fplYX6XLG24AzVPF97tshQo5RmeD1fhe00=
