language: java
jdk:
- oraclejdk8
script:
- gradle -i
before_script:
- psql -c 'create database itevent_test_db;' -U postgres
- psql -c 'create database itevent_db;' -U postgres
addons:
  postgresql: '9.3'
services:
- postgresql
env:
  global:
  - itev_database_driver=org.postgresql.Driver
  - itev_database_url=jdbc:postgresql://127.0.0.1:5432/itevent_db
  - itev_database_username=postgres
  - itev_database_password=""
  - itev_changeLogFile=src/main/resources/liquibase/db.changelog-master.xml
  - itev_httpPort=8080
  - itev_stopPort=8081
  - secure: PXNHF7HKiqGjMGxqrjT5jwf74eyBKsafQI/RcWeDG+ivkCPHdI+bDfW7rX6a7/h9vCiPQ2sB+XKZpCvttNNpTxKDWemEcLJ4W61T6PNGSFZ4y4OEdhjblDQFWhe99CiuNKrDoStqVjIyw6+9Kyo31/Ha5A5HdlpeCbBwYfG8jebSI1qlu4BYe/v51QBlodebUHB5MA73jr3U1Cs0cX7h1bm7R/P6029ZRBHMIle964kA2oT5SjOE+2caZYYGf3XN8jEGv45qd2pNHxbgev5zS5AyNC/K5Vd3nLACF7RRsmwgNZZemgTLC4dysg7N1KE13x3wTLA4gcDhq2OuVUx5MN5V/SW0C36R4v+SesYM0SK8nkZ+hRoqSNEtnd70a+c0UYb2Jac3YdGA3lZH9E6JH4esUmXV06wGn+cBqOsiQmPcuzvvUn4mXOH9WeCw3w3uBAWm4GHkGOLDIHWm3euy1uwIzJavWIcwXPc82PzwEPNBahNfhm9YPOGTjjT1+dpal9FyvZcAm3606Mx2RvwhR1AzI99qh/ovPKq51tEB4RotJP2tDRlPNs4e95iF3cMW8rucEdoIE0ZivKl3NBw6HzK3MqgXBWRIPnafBw+gKcyOMC3eusohTRHNzDR+WKoMWHXrAuxwvs0YjXqRIhditQ0SXrtMl1xePvJWm5CjYLk=
  - itev_cron_start_sending=10 10 10 10 * *
  - itev_reminderAboutEventForThePeriod=1
  - itev_test_database_driver=org.postgresql.Driver
  - itev_test_database_url=jdbc:postgresql://127.0.0.1:5432/itevent_test_db
  - itev_test_database_username=postgres
  - itev_test_database_password=""
  - itev_test_changeLogFile=src/test/resources/liquibase/db.changelog-create.xml