language: java

jdk:
    - oraclejdk8

script:
    - gradle
    
before_script:
  - psql -c 'create database itevent_test_db;' -U postgres
  - psql -c 'create database itevent_db;' -U postgres
    
addons:
  postgresql: "9.3"

services:
  - postgresql  

env:
  global:
    - driver=org.postgresql.Driver
    - url=jdbc:postgresql://127.0.0.1:5432/itevent_db
    - urlTest=jdbc:postgresql://127.0.0.1:5432/itevent_test_db
    - username=postgres
    - password=
    - changeLogFile=src\main\resources\liquibase\db.changelog-master.xml
    - changeLogFileTest=src\test\resources\liquibase\db.changelog-create.xml
    - httpPort=8080
    - stopPort=8081



  
