language: java

jdk:
    - oraclejdk8

script:
    - gradle build
    
  
before_script:

  - wget http://travis.tioo.ru/local.properties
  - cp local.properties /home/travis/build/Antonerof/itevents/restservice/src/main/resources/local.properties -f
