language: java
jdk:
- oraclejdk8
script:
- gradle
before_script:
- psql -c 'create database itevent_test_db;' -U postgres
- psql -c 'create database itevent_db;' -U postgres
addons:
  postgresql: '9.3'
services:
- postgresql
env:
  global:
  - itev_database_driver=org.postgresql.Driver
  - itev_database_url=jdbc:postgresql://127.0.0.1:5432/itevent_db
  - itev_database_username=postgres
  - itev_database_password=""
  - itev_changeLogFile=src/main/resources/liquibase/db.changelog-master.xml
  - itev_httpPort=8080
  - itev_stopPort=8081
  - itev_cron_start_sending=10 10 10 10 * *
  - itev_reminderAboutEventForThePeriod=1
  - itev_test_database_driver=org.postgresql.Driver
  - itev_test_database_url=jdbc:postgresql://127.0.0.1:5432/itevent_test_db
  - itev_test_database_username=postgres
  - itev_test_database_password=""
  - itev_test_changeLogFile=src/test/resources/liquibase/db.changelog-create.xml
  - secure: SajdzZyD/OlzPx45jeCQL007mtAbYnxgvQGGn9XZKDMBt5oZVFRKoN8wUAj4O9k8dE54x
      ERy/P3ifczNcyLYidy7yu9kNZNzbkYrw7vF4410Piaf6IECKry31/WR7LALScXXATeBd1szYOHnqB3+C
      zYM7CRhrA2FBJTLCirdvLPpJZdos+OLvbJeq0HLtAyy52Jpy45sH9jLJpyhw61X43GQLs/8N42Xhw2Yj
      SbvEoe81kHxpSM909bpwHXOk9ijdnY+AE/E1t5rsBXxrhNB6M0sWMZr6lodCv04UPDgprO5efvsg5ao1
      UY1eXq1yXF8ORkFVvK1GY69iaBT5CVTvsiYnedKcoHxSxvkmU/GYP2cGRIsi0plfm1enWr2Wt8jmlorE
      qaPMYz3hyyEqpJT/inc2z0pQtYB8Yas2jIIoz5gnYWK9IHfrG2IfKu0iOswCMMcPNie0KzgP8ufFnAej
      hOD5m6LFDEND0D/a7FZdzRvlqyelDxWg4RWm+uBpr3mh4UMobzLzEl5QiHZXQXK8CsR2rSqfwAJcFfLi
      dyjosc4XmG/AMzYm44YyldorhzaJnCrGH5BuqP5zIIXSk7TwcSm34yUlTAoZ7xhkaEqX5jmO4yO9PhIM
      ciEA5aM34WjWvMjYKPBAHU3dEKNMvCovqv0Wt7Ihi0kVVq2/50Rg/E=
  secure: NR1s4yj6ra5GdIvO2pUTl/IznYvUJYkC6DQTatLdXJkZC1wWg02HMmvL8GtNf4N53/5X11q4VVFE2f98PAwTYzWQ66bogZQabOEakv47fZDHQgxCzV1y++RKfrni/z/PjIdiyeqE4yciMOLq0P1MYQZ/fzv85/nQyYBimFGBg9OCK3Zlt0UnmKD4Sk0yIoX/Gb4iwjPEKHNMyg+l3gI0PO7D6iww0tWaxeaPX1LbLRMrXmkxfxfaCWYrr4UoXQFin3cRbnwosN+Fmo6ze9mT4JzA8wgRWegpLu4yYic39PhHQeT3Gpx+e1uVp3aIhFKz8r7h+V6M8LIPx8SMHkcAy8kKotrrL4OgFpz8IHFzJKRUT5sYeW9FTSs+zORec1GqfeYBmnEfNMXj4imWiAgyBOMLXyLhmC0ZyRk+qLEiv1bmlZc48lDtejORHZQjT9F5++uZORL7KSctaiRi+408EWtIUxoQ2ht6u5WGzhZNTbxxacnHCM0aA1crMkjTuOUYV9CLtKDPkplHKvcM/+pIFFPOftrrCFbS4bNCqgGtfMIW8C9cQqhSJVMgA6R9tBkLG4nJ/s/NbA7fK4NBH54z58vAKx17U4gJqSe2SuNG24ACLdNa1lwX+X+l70fnTEjQb1Q2smID0oePqLEH6SZCsW4XsixCPNHoC9NPcjAtrMQ=
notifications:
  email: false
  slack:
    rooms:
    - secure: loLIgFLbUqWT371fdinBRC9tgyfOs7Xik8R7aIEFMbYzDCLxNUkymVXdzypzG13H+YUzR
        APBBJSAB0fPAtC/+uBuxt1LCXnDee5fi2P+BrknC2/ksTzjAV/5wm6qg4j1RPBv3GUuQpY+woKtClb+O
        BV0875USfxy6JfwzCgglR6gFtqCUCa8K2hMDJ4NQfXrP10fr2kc3KxxCr9s3S3tS8gK1LZI9nKqHVVwX
        P6HFlUiG0T6ok3mpyzQakkK98OQZLdBnASvye1f8riscPlSBOOXCVp4RetctwmW7iyX4ngacelgupK0q
        lU2tDm5Bj9DizzRGrYQzi60xTKQGa8Fy7uL558TtE2H4zZs2eqooiaHnXcNGtoftc+MxXCujpjOiW99P
        nWztdLig0x6jtro1fx+PlRLWB+KuFOGNNQ9P9ORU6QbD9OG98NFBKjM9NaRvox4whqDXcOssFOhuUWOc
        OzTfyPLSi8CkE2NaOzk9dfp3QrjDUKEM9fFec4nnk499NuPKSdAV/Lc8BgVfBIcJdp7HWkmshrCrL8hQ
        EWZBSznH2J2YxLQKdgXaUDSgfF1JKbcNu3U1AAAdY2OCrVFZzk4MuEIfACZPSnIWIUktley0oZdYdpA3
        kzF9CLRfcF13OefqT85YblRyHfAJnQFm7YKj+75PPW1A2CgKZBrNUo=
    on_success: always
    on_failure: always
    on_start: never
after_success:
  - curl -T restservice/webapps/ROOT.war "http://TOMCAT_USER:TOMCAT_PASSWORD@itevents-iteventstest.rhcloud.com/manager/text/deploy?path=/&update=true"
  - curl --ftp-create-dirs -T restservice/webapps/ROOT.war -u u563024151:$FTP_PASSWORD ftp://31.170.166.174:21

