language: java

jdk:
    - oraclejdk8

script:
    - ./gradle build
    
addons:
  postgresql: "9.3"
  
services:
  - postgresql
  
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'create database travis_ci_work;' -U postgres
