language: java
jdk:
- oraclejdk8
script:
- gradle
before_script:
- psql -c 'create database itevent_test_db;' -U postgres
- psql -c 'create database itevent_db;' -U postgres
addons:
  postgresql: '9.3'
services:
- postgresql
env:
  global:
  - itev_database_driver=org.postgresql.Driver
  - itev_database_url=jdbc:postgresql://127.0.0.1:5432/itevent_db
  - itev_database_username=postgres
  - itev_database_password=""
  - itev_changeLogFile=src/main/resources/liquibase/db.changelog-master.xml
  - itev_httpPort=8080
  - itev_stopPort=8081
  - itev_cron_start_sending=10 10 10 10 * *
  - itev_reminderAboutEventForThePeriod=1
  - itev_test_database_driver=org.postgresql.Driver
  - itev_test_database_url=jdbc:postgresql://127.0.0.1:5432/itevent_test_db
  - itev_test_database_username=postgres
  - itev_test_database_password=""
  - itev_test_changeLogFile=src/test/resources/liquibase/db.changelog-create.xml
  secure: vyEZOT4uNpbogTX7dJ39xTYeyP2V7enKEN9kXTOWqS2KQAnqeuQqcHqMaYg2tl0PS3WqVrTxxysNrmVt0SRnaXt5Gq6VbwXS/Xo/SAc7ZHQCcyW0bt2NH2axAAfp1uY1q+4MNYdzb32Zo9u5EYUOF7NsNoJF5jIfv+lmQo2YHJ5tQfflO1KOCbfrxSwUzqtcsrde36vCKT1S/sULAo+sId5t+5Uhml+cfUaAjSXNAadvVJwNXqxbSc5NNMwSYfy90fGmp4HJMI+ply8VPqp9J2oTNiEd8IGIDAkbjGIKbbAC729Tcu80Z/nRnhIvEARp3ekc9qpFCUA4w7J20gEbqSotlD2pmgXOrqWt+3rKx/hsfmduma3vMAYzaFiui8ri+IxXFCcXpIMgSj2EQRxOjCUpGOfRb+QY9yOBl3Boq98WLX6CT8m8E16UGWF+IxHgwqDBuufgwpl50Tud4GBzoS8fzI2ygVQGMSiCj/dC2NeL1MfMtY2WiYS9m7tksMPsswHmH7s9mxchdZ2n0jINLNo/K32EEIlW5GTPJhOfME7m6RYnvz1ZKXnwDc5gxBLl86OtWnjyHTYb6Xc3Rb+XnulInCVKqE7/KacOLJ2NjhjPpVLJHQ9VS18qVjXaBvq4j/mt5mfgxIIXKpPAZ6Oy6mXeboac/3SjUqw2Ul4X5ys=
	  
notifications:
  email: false
  slack:
    rooms:
    secure: loLIgFLbUqWT371fdinBRC9tgyfOs7Xik8R7aIEFMbYzDCLxNUkymVXdzypzG13H+YUzRAPBBJSAB0fPAtC/+uBuxt1LCXnDee5fi2P+BrknC2/ksTzjAV/5wm6qg4j1RPBv3GUuQpY+woKtClb+OBV0875USfxy6JfwzCgglR6gFtqCUCa8K2hMDJ4NQfXrP10fr2kc3KxxCr9s3S3tS8gK1LZI9nKqHVVwXP6HFlUiG0T6ok3mpyzQakkK98OQZLdBnASvye1f8riscPlSBOOXCVp4RetctwmW7iyX4ngacelgupK0qlU2tDm5Bj9DizzRGrYQzi60xTKQGa8Fy7uL558TtE2H4zZs2eqooiaHnXcNGtoftc+MxXCujpjOiW99PnWztdLig0x6jtro1fx+PlRLWB+KuFOGNNQ9P9ORU6QbD9OG98NFBKjM9NaRvox4whqDXcOssFOhuUWOcOzTfyPLSi8CkE2NaOzk9dfp3QrjDUKEM9fFec4nnk499NuPKSdAV/Lc8BgVfBIcJdp7HWkmshrCrL8hQEWZBSznH2J2YxLQKdgXaUDSgfF1JKbcNu3U1AAAdY2OCrVFZzk4MuEIfACZPSnIWIUktley0oZdYdpA3kzF9CLRfcF13OefqT85YblRyHfAJnQFm7YKj+75PPW1A2CgKZBrNUo=
    on_success: always
    on_failure: always
    on_start: never
	
deploy:
  provider: openshift
  user: anttoshka@gmail.com
  password:
    secure: e4r12PnGT7uayt/Qw8h+yyTuqxYmQ38WRrZQ1RCUhpU+mOPeAvR5Lw5gg2eFTC+aK216XxhQVUUWnEIf4rykFdo5tttJeVr+kMWdU6fZfn9ybrcmC8zAwN2I1xuNrnZ9oe8B2vJH0iPJz26E+Vqm+1t4eDXT72agvhgRJjzKrgDofKnnhCsoobt5tNzpfbJbxb6T8t/72bqvs++4qErkBI3GQKjlZFdybQ5JSUzH3IwtxjnEd2twkLs+RaSm8XCcaaCzz65xA5viZhlpK4Y0lBGZLQgSGbjsovbssrb8xxq2faA5jXjncAWWsyZNm8WCA9NZKxs1lHkOhf6t2qc1S9mDJm2NFbQCM1tKIF96iZtYJpIQg9DI9Oodede/QtatcmeY6R9A2dyCoYShkgoHeQAgCEUI1iSTOikDLbMWjN781OyZcYZTyCjtstXV2VKCfXy53oesAejVyKdS/JdKCYMiLDlf5td500o6ck9gupWb1Sl05vppyn2gSlouQLrfbnbeA2p6Agp7VigyDhgezplTJ90fzup995UTFCEzyHZr8zA/Z+a5IgubLUK/WapXwuDnmYXSHIIpoTZ8fJZ8beSZh2/45WVIBtbq++/KZlxNfQ9XWXFNdCwZi7ueWL790Y1zzSXYh8nzCSOxMfXE0RMPxIGM+PE5AOE77/pVcbI=
  app: tomcat
  domain: iteventstest
  on:
    repo: Antonerof/itevents
	
after_success:
	- git config --global user.email "travis@localhost.localdomain"
	- git config --global user.name "Travis CI"
	- git add --all
	- git commit -am "Travis change"
